avto1701-main/avto_market/account/urls.py
from django.urls import path, include
from django.contrib.auth import views 
from .import views 


app_name = 'account'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name="register"  ),
    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('messages_view/', views.messages_view, name='messages_view'),
    path("messages_detail/<int:messages_id>", views.messages_detail, name="messages_detail"),
    path("send_message/", views.send_message, name="send_message"),
    path("change_password/", views.change_password, name="change_password"),
    path("password_change_done/", views.password_change_done, name="password_change_done"),
    
]

avto1701-main/avto_market/auction/urls.py
from django.urls import path, include
from django.contrib.auth import views 
from .import views 

app_name = 'auction'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('avto/<int:avto_id>/auction_create/', views.auction_create, name="auction_create"  ),
    path('auctions/', views.view_all_auctions, name='view_all_auctions'),
    path('view_user_auctions/', views.view_user_auctions, name='view_user_auctions'),
    path("edit_auction/<int:auction_id>", views.edit_auction, name="edit_auction"),
    path('create_buyer/<int:auction_id>/<int:user_id>/', views.create_buyer, name='create_buyer'),
    path('comment_create/<int:auction_id>/<int:user_id>/', views.comment_create, name='comment_create'),
    path("auction_detail/<int:auction_id>", views.auction_detail, name="auction_detail"),
    path('winner/<int:auction_id>/', views.winner, name='winner'),
    path('profile_win/<str:username>', views.profile_win, name='profile_win'),
]

avto1701-main/avto_market/avto/urls.py
from django.urls import path
from .import views

app_name = 'avto'

urlpatterns = [
    path("", views.index, name="index"),
    path("avto_list/", views.avto_list, name="avto_list"),
    path("avto_detail/<int:avto_id>", views.avto_detail, name="avto_detail"),
    path("new_avto/", views.new_avto, name="new_avto"),
    path("user_avto/", views.user_avto, name="user_avto"),
    path("edit_avto/<int:avto_id>", views.edit_avto, name="edit_avto"),
    path("delete_avto/<int:avto_id>", views.delete_avto, name="delete_avto"),
]

avto1701-main/avto_market/avto_market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("avto.urls")),
    path('account/', include('account.urls')),
    path('auction/', include('auction.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

avto1701-main/avto_market/avto/models.py
from django.db import models
from django.contrib.auth.models import User


class Avto(models.Model):
    
    BRAND_CHOICES = (
        ('audi', 'Ауди'),
        ('bmw', 'БМВ'),
        ('honda', 'Хонда'),
        ('mazda', 'Мазда'),
        ('mercedes', 'Мерседес'),
        ('nissan', 'Ниссан'),
        ('toyota', 'Тойота'),
    )
    
    STEERING_CHOICES = (
        ('left', 'Левосторонний'),
        ('right', 'Правосторонний'),
    )

    TRANSMISSION_CHOICES = (
        ('manual', 'Механика'),
        ('automatic', 'Автомат'),
        ('robot', 'Робот'),
    )
    
    DRIVE_CHOICES = (
        ('front', 'Передний'),
        ('rear', 'Задний'),
        ('4wd', '4 WD'),
    )
    
    FUEL_CHOICES = (
        ('gasoline', 'Бензин'),
        ('diesel', 'Дизель'),
        ('gas', 'Газ'),
        ('electric', 'Электро'),
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    brand = models.CharField(max_length=20, choices=BRAND_CHOICES)
    city = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    year = models.IntegerField()
    price = models.DecimalField(max_digits=15, decimal_places=2)
    steering = models.CharField(max_length=10, choices=STEERING_CHOICES)
    mileage = models.IntegerField()
    transmission = models.CharField(max_length=10, choices=TRANSMISSION_CHOICES)  # поле с виджетом КПП
    drive = models.CharField(max_length=10, choices=DRIVE_CHOICES)  # поле с виджетом привод
    fuel = models.CharField(max_length=10, choices=FUEL_CHOICES)  # поле с виджетом топливо
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='avtoimg/%Y/%m/%d', blank=True)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self. brand

avto1701-main/avto_market/avto/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Avto
from django.contrib.auth.decorators import login_required
from .form import AvtoForm
from django.http import Http404, HttpResponseForbidden

def index(request):
    return render (request,'avto/index.html')

def avto_list(request):
    avtos = Avto.objects.filter(active= True)
    return render(request, 'avto/avto_list.html', {'avtos': avtos})

def avto_detail(request, avto_id):
    avto = get_object_or_404(Avto, id=avto_id)
    return render(request, 'avto/avto_detail.html', {'avto': avto})


@login_required
def new_avto(request):
    if request.method == 'POST':
        form = AvtoForm(request.POST , request.FILES)
        if form.is_valid():
            avto = form.save(commit=False)
            avto.author = request.user
            avto.save()
            return redirect('avto:user_avto')
    else:
        form = AvtoForm()
    
    return render(request, 'avto/new_avto.html', {'form': form})

@login_required
def user_avto(request):
    avtos = Avto.objects.filter(author = request.user)
    context = {"avtos": avtos}
    return render(request,'avto/user_avto.html', context )


@login_required
def edit_avto(request):
    avtos = Avto.objects.filter(author = request.user)
    context = {"avtos": avtos}
    return render(request,'avto/user_avto.html', context )

@login_required
def edit_avto(request, avto_id):
    avto = get_object_or_404(Avto, id=avto_id)
    if avto.author != request.user:
        raise Http404
    if request.method == 'POST':
        form = AvtoForm(request.POST, request.FILES, instance=avto)
        if form.is_valid():
            avto = form.save(commit=False)
            avto.author = request.user
            avto.save()
            return redirect('avto:user_avto')
    else:
        form = AvtoForm(instance=avto)
    
    return render(request, 'avto/edit_avto.html', {'form': form})

@login_required
def delete_avto(request, avto_id):
    avto = get_object_or_404(Avto, id=avto_id)

    if avto.author != request.user:
        return HttpResponseForbidden("У вас нет прав для удаления этого объявления.")

    if request.method == "POST":
        avto.delete()
        return redirect("avto:user_avto")

    context = {"avto": avto}
    return render(request, 'avto/delete_avto.html', context)

avto1701-main/avto_market/avto/templates/avto/avto_detail.html
{% extends 'avto/base.html' %}
{% load static %}

{% block content1 %}

<head>
    <title>{{ avto.brand }} {{ avto.model }}</title>
    <style>


        .title {
            color: #bdc55f;
            font-size: 24px;
            font-weight: bold;
            box-shadow: 0 0 15px white;
            padding: 0.5%;
            background: rgba(0, 0, 0, 0.8);
        }

        .info {
            color: #bdc55f;
            font-size: 16px;
            margin-bottom: 10px;
            font-weight: bold;
            box-shadow: 0 0 15px white;
            padding: 0.5%;
            background: rgba(0, 0, 0, 0.8);
            
        }

        .image {
            max-width: 70%;
            height: auto;
            margin-top: 10px;
            border-radius: 8px;
            box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
            border: 5px solid black;
            box-shadow: 0 0 15px white;
        }

        .auction-link {
            display: inline-block;
            background-color: #4d1911;;
            color: yellow;
            padding: 10px 20px;
            text-decoration: none;
            font-weight: bold;
            border-radius: 4px;
            margin-top: 10px;
            float: left;
        }

        .auction-link:hover {
            background-color: #333;
        }
    </style>
</head>
<body>
    <div>
    <h1 class="title">{{ avto.brand }} {{ avto.model }}</h1>
    <p class="info"><strong>Год выпуска:</strong> <span style="color:white">{{ avto.year }}</style></p>
    <p class="info"><strong>Цена:</strong> <span style="color:white">{{ avto.price }}</style></p>
    <p class="info"><strong>Руль:</strong><span style="color:white"> {{ avto.get_steering_display }}</style></p>
    <p class="info"><strong>Пробег:</strong> <span style="color:white">{{ avto.mileage }}</style></p>
    <p class="info"><strong>Трансмиссия:</strong><span style="color:white"> {{ avto.get_transmission_display }}</style></p>
    <p class="info"><strong>Привод:</strong> <span style="color:white">{{ avto.get_drive_display }}</style></p>
    <p class="info"><strong>Топливо:</strong><span style="color:white"> {{ avto.get_fuel_display }}</style></p>
    <p class="info"><strong>Дата размещения: </strong><span style="color:white">{{ avto.created|date:"Y-m-d" }}</style></p>
    {% if avto.description %}
        <p class="info">Описание: <span style="color:white">{{ avto.description }}</style></p>
    {% endif %}
    {% if avto.image %}
        <img class="image" src="{{ avto.image.url }}" alt="Car Image">
    {% endif %}
    <div style="clear: both;"></div>
</body>
</html>

{% endblock %}

avto1701-main/avto_market/avto/templates/avto/avto_list.html
{% extends 'avto/base.html' %}
{% load static %}



{% block content1 %} 

<style>
  @media (max-width: 767px) {
    .card-container {
      display: flex;
      justify-content: center;
      flex-wrap: wrap;
    }
    
    .card {
      width: 100%;
      margin: 10px;
      max-width: 300px;  /* Ограничиваем ширину карточки на мобильных устройствах */
    }
  }
  </style>

  <div class="card-container">
    {% for avto in avtos %}
      <div class="card">
        <a href="{% url 'avto:avto_detail' avto.id %}">
          <div class="card-image">
           <img src="{% if avto.image %}{{ avto.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="{{ avto.brand }} {{ avto.model }}">
          </div>
          <div class="card-details">
            <h3>{{ avto.brand }}</h3>
            <p>{{ avto.model }}</p>
            <p>Год выпуска: {{ avto.year }}</p>
            <p>Цена: {{ avto.price }}</p>
            <p>Дата создания: {{ avto.created|date:"F j, Y" }}</p>
          </div>
        </a>
      </div>
    {% empty %}
      <p>Лоты отсутствуют</p>
    {% endfor %}
  </div>

{% endblock %}

avto1701-main/avto_market/avto/templates/avto/base.html
{% load static %} 
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Аукцион</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
  <header>
    <nav>
      <input type="checkbox" id="burger-checkbox">
      <label for="burger-checkbox" class="burger-icon">
        <span></span>
        <span></span>
        <span></span>
      </label>
      <ul class="menu">
        {% if user.is_authenticated %}
        <li>Привет, {{user.username}}.</li>
        <li><a href="{% url 'account:profile' %}">Мой профиль</a></li>
        <li><a href="{% url 'avto:user_avto' %}">Мои объявления</a></li>
        <li><a href="{% url 'account:messages_view' %}">Мои сообщения</a></li>
        <li><a href="{% url 'auction:view_all_auctions' %}">Активные аукционы</a></li>
        <li><a href="{% url 'avto:avto_list' %}">Лоты</a></li>
        <li><a href="{% url 'account:logout' %}">Выйти</a></li>
        {% else %}
        <li><a href="{% url 'account:register' %}">Регистрация</a></li>
        <li><a href="{% url 'account:login' %}">Авторизироваться</a></li>
        <li><a href="{% url 'avto:avto_list' %}">Лоты</a></li>
        <li><a href="{% url 'avto:index' %}">Главная</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>

  <main>
    <div class="container">
      {% block content1 %}
      {% endblock %}
    </div>
    <div class="container">
      {% block content2 %}
      {% endblock %}
    </div>
  </main>

  <footer>
    <p>© Авто аукцион</p>
  </footer>

  <script >
    const burgerCheckbox = document.getElementById('burger-checkbox');
const menu = document.querySelector('.menu');

// Закрываем меню по клику на ссылку
menu.addEventListener('click', (e) => {
  if (e.target.tagName === 'A') {
    burgerCheckbox.checked = false;
  }
});

// Закрываем меню при клике вне меню
document.addEventListener('click', (e) => {
  if (!e.target.closest('nav')) {
    burgerCheckbox.checked = false;
  }
});



  </script>
</body>
</html>

avto1701-main/avto_market/avto/templates/avto/delete_avto.html
{% extends 'avto/base.html' %}


{% block content1 %}
<style>
  /* CSS стили здесь */
  .content {
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    background-color: #f2f2f2;
    border-radius: 5px;
    box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.1);
  }

  .content h1 {
    color: #333;
    font-size: 24px;
    margin-bottom: 10px;
  }

  .content p {
    color: black;
    font-size: 16px;
    margin-bottom: 20px;
  }

  .content form {
    display: flex;
    flex-direction: column;
    border: 2px solid #333;
    padding: 20px;
  }

  .content label,
  .content input,
  .content button {
    margin-bottom: 10px;
  }

  .content label {
    font-weight: bold;
  }

  .content input {
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    background-color: #000000;
    color: #fff;
  }

  .content button {
    padding: 10px 20px;
    background-color: #333;
    color: #fff;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .content input:hover {
    background-color: red;
    color: black;
    font-size: 14px;
    font-weight: bold;
    border: 3px solid black;
  }

  .content input[type="text"],
  .content input[type="email"] {
    border: 1px solid #777;
    background-color: #fff;
    color: #000;
  }

  .container {
    min-height: 41vh;
  }

</style>
</head>
<body>
<div class="content">
  <h1>Удаление объявления</h1>
  <p>Вы действительно хотите удалить объявление "{{ avto.brand }} {{ avto.model }}"?</p>
  <form action="{% url 'avto:delete_avto' avto.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
  </form>
</div>
</body>
</html>
{% endblock %}

avto1701-main/avto_market/avto/templates/avto/edit_avto.html
{% extends "avto/base.html" %}


{% block content1 %}
<style>
  .form-container {
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    background-color: #f2f2f2;
    border-radius: 5px;
    box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.1);
  }

  .form-container form {
    display: flex;
    flex-direction: column;
    border: 2px solid #333;
    padding: 20px;
  }

  .form-container label,
  .form-container input,
  .form-container button {
    margin-bottom: 10px;
  }

  .form-container label {
    font-weight: bold;
  }

  .form-container input {
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    background-color: white;
  }

  .form-container button {
    padding: 10px 20px;
    background-color: #333;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .form-container button:hover {
    background-color: #555;
  }

  .form-container input[type="text"],
  .form-container input[type="email"] {
    border: 1px solid #777;
    background-color: white;
    color: black;
  }
</style>

<div class="form-container">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Сохранить</button>
  </form>
</div>
{% endblock %}  

avto1701-main/avto_market/avto/templates/avto/index.html
{% load static %} 
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Аукцион</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <header >
    <h1 style="text-align: center; color: #FFF; text-shadow: 0 0 4px #FFF; font-size: 2.5em;">Авто аукцион</h1>
    <nav >
      <ul >
        <li><a href="{% url 'account:register' %}">Регистрация</a></li>
        <li><a href="{% url "account:login" %}">Вход</a></li>
        <li><a href="{% url 'avto:avto_list' %}">Лоты</a></li>
      </ul>
    </nav>
  </header>

  

  <div class="image">
    <img src="{% static 'img/красивая_девушка.jpg' %}" alt="Красивая девушка">
  </div>

  <footer>
    <p>© 2024 Авто аукцион</p>
  </footer>

  <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

avto1701-main/avto_market/avto/templates/avto/new_avto.html
{% extends "avto/base.html" %}

{% block content1 %}
<style>
  .form-container {
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    background-color: #f2f2f2;
    border-radius: 5px;
    box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.1);
  }

  .form-container form {
    display: flex;
    flex-direction: column;
    border: 2px solid #333;
    padding: 20px;
  }

  .form-container label,
  .form-container input,
  .form-container button {
    margin-bottom: 10px;
  }

  .form-container label {
    font-weight: bold;
  }

  .form-container input {
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    background-color: white;
  }

  .form-container button {
    padding: 10px 20px;
    background-color: #333;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .form-container button:hover {
    background-color: #555;
  }

  .form-container input[type="text"],
  .form-container input[type="email"] {
    border: 1px solid #777;
    background-color: white;
    color: black;

  }

  @media (max-width: 767px) {
    .form-container {
      max-width: 300px; /* Ограничиваем максимальную ширину формы на мобильных устройствах */
      margin: 0 auto; /* Центрируем форму по горизонтали */
      padding: 10px; /* Добавляем небольшой отступ вокруг формы */
    }
  }
  
</style>

<div class="form-container">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Сохранить</button>
  </form>
</div>

{% endblock %}

avto1701-main/avto_market/avto/templates/avto/user_avto.html
{% extends 'avto/base.html' %}
{% load static %}

{% block content1 %}
  <style>
    .edit-button {
      background-color: #000000;
      color: white;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      text-decoration: none;
      font-size: 16px;
      font-weight: bold;
      cursor: pointer;
      margin-bottom: 30px;
    }

    .edit-button:hover {
      background-color: white;
      color: black;
      border: 3px solid black;
      font-size: 17px;
    }

    .red-bottom {
      background-color: #4d1911;;
      color: yellow;
      border: 0.5px solid black;
      padding: 10px 20px;
      border-radius: 5px;
      text-decoration: none;
      font-size: 16px;
      font-weight: bold;
      cursor: pointer;
      margin-bottom: 30px;
    }

    .red-bottom:hover {
      background-color: yellow;
      color: black;
      border: 3px solid black;
      font-size: 17px;
      font-weight: bold;
    }


    .container {
      min-height: 42vh;
    }

    @media (max-width: 767px) {
      .card-container {
        display: flex;
        justify-content: center;
        flex-wrap: wrap;
      }
      
      .card {
        width: 100%;
        margin: 10px;
      }
     
      .red-bottom {
        background-color: #4d1911;;
        color: yellow;
        border: 0.5px solid black;
        padding: 10px 20px;
        border-radius: 5px;
        text-decoration: none;
        font-size: 12px;
        font-weight: bold;
        cursor: pointer;
        margin-bottom: 30px;
      }


    }

  </style>

  <p style="margin-bottom: 30px;"><a href="{% url 'avto:new_avto' %}" class="red-bottom">Добавить объявление</a>
    <a  href="{% url 'auction:view_user_auctions' %}" class="red-bottom" >Мои аукционы</a>
  
  </p>
    
  
 

  <div class="card-container">
    {% for avto in avtos %}
      <div class="card">
        <a href="{% url 'avto:avto_detail' avto.id %}">
          <div class="card-image">
            <img src="{% if avto.image %}{{ avto.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="{{ avto.brand }} {{ avto.model }}">
          </div>
          <div class="card-details">
            <h3>{{ avto.brand }}</h3>
            <p>{{ avto.model }}</p>
            <p>Год выпуска: {{ avto.year }}</p>
            <p>Цена: {{ avto.price }}</p>
            <p>Дата создания: {{ avto.created|date:"F j, Y" }}</p>
          </div>
        </a>
        <p style="margin-top: 20px ; color: white;"><a href="{% url 'auction:auction_create' avto.id%}" class="edit-button" >Создать аукцион</a></p>
        <p style="margin-top: 30px ; color: white;"><a href="{% url 'avto:edit_avto' avto.id %}" class="edit-button" >Изменить объявление</a></p>
        <p style="margin-top: 30px ;color: white;"><a href="{% url 'avto:delete_avto' avto.id %}" class="edit-button">Удалить объявление</a></p>
        
      </div>
    {% empty %}
      <p>Лоты отсутствуют</p>
    {% endfor %}
  </div>

  

{% endblock %}