avto1701-main/avto_market/auction/urls.py
from django.urls import path, include
from django.contrib.auth import views 
from .import views 

app_name = 'auction'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('avto/<int:avto_id>/auction_create/', views.auction_create, name="auction_create"  ),
    path('auctions/', views.view_all_auctions, name='view_all_auctions'),
    path('view_user_auctions/', views.view_user_auctions, name='view_user_auctions'),
    path("edit_auction/<int:auction_id>", views.edit_auction, name="edit_auction"),
    path('create_buyer/<int:auction_id>/<int:user_id>/', views.create_buyer, name='create_buyer'),
    path('comment_create/<int:auction_id>/<int:user_id>/', views.comment_create, name='comment_create'),
    path("auction_detail/<int:auction_id>", views.auction_detail, name="auction_detail"),
    path('winner/<int:auction_id>/', views.winner, name='winner'),
    path('profile_win/<str:username>', views.profile_win, name='profile_win'),
]

avto1701-main/avto_market/avto/urls.py
from django.urls import path
from .import views

app_name = 'avto'

urlpatterns = [
    path("", views.index, name="index"),
    path("avto_list/", views.avto_list, name="avto_list"),
    path("avto_detail/<int:avto_id>", views.avto_detail, name="avto_detail"),
    path("new_avto/", views.new_avto, name="new_avto"),
    path("user_avto/", views.user_avto, name="user_avto"),
    path("edit_avto/<int:avto_id>", views.edit_avto, name="edit_avto"),
    path("delete_avto/<int:avto_id>", views.delete_avto, name="delete_avto"),
]

avto1701-main/avto_market/avto_market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("avto.urls")),
    path('account/', include('account.urls')),
    path('auction/', include('auction.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

avto1701-main/avto_market/auction/models.py
from django.db import models
from django.contrib.auth.models import User
from avto.models import Avto
from django.core.exceptions import ValidationError
from django.shortcuts import redirect



class Auction(models.Model):
    avto = models.OneToOneField(Avto, on_delete=models.CASCADE, related_name='auction')
    start_price = models.DecimalField(max_digits=15, decimal_places=2)
    end_time = models.DateTimeField(help_text='YYYY-MM-DD HH:MM:SS')
    active = models.BooleanField(default=True)

    def __str__(self):
        return  self.avto.brand


class Buyer(models.Model):
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name='buyers')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    last_bid_price = models.DecimalField(max_digits=15, decimal_places=2)
    updated_at = models.DateTimeField(auto_now=True)
   
        
    def __str__(self):
        return str(self.last_bid_price)
    
    class Meta:
        ordering = ['-last_bid_price']
    
class Comment(models.Model):
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-created_at']

avto1701-main/avto_market/avto/models.py
from django.db import models
from django.contrib.auth.models import User


class Avto(models.Model):
    
    BRAND_CHOICES = (
        ('audi', 'Ауди'),
        ('bmw', 'БМВ'),
        ('honda', 'Хонда'),
        ('mazda', 'Мазда'),
        ('mercedes', 'Мерседес'),
        ('nissan', 'Ниссан'),
        ('toyota', 'Тойота'),
    )
    
    STEERING_CHOICES = (
        ('left', 'Левосторонний'),
        ('right', 'Правосторонний'),
    )

    TRANSMISSION_CHOICES = (
        ('manual', 'Механика'),
        ('automatic', 'Автомат'),
        ('robot', 'Робот'),
    )
    
    DRIVE_CHOICES = (
        ('front', 'Передний'),
        ('rear', 'Задний'),
        ('4wd', '4 WD'),
    )
    
    FUEL_CHOICES = (
        ('gasoline', 'Бензин'),
        ('diesel', 'Дизель'),
        ('gas', 'Газ'),
        ('electric', 'Электро'),
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    brand = models.CharField(max_length=20, choices=BRAND_CHOICES)
    city = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    year = models.IntegerField()
    price = models.DecimalField(max_digits=15, decimal_places=2)
    steering = models.CharField(max_length=10, choices=STEERING_CHOICES)
    mileage = models.IntegerField()
    transmission = models.CharField(max_length=10, choices=TRANSMISSION_CHOICES)  # поле с виджетом КПП
    drive = models.CharField(max_length=10, choices=DRIVE_CHOICES)  # поле с виджетом привод
    fuel = models.CharField(max_length=10, choices=FUEL_CHOICES)  # поле с виджетом топливо
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='avtoimg/%Y/%m/%d', blank=True)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self. brand

avto1701-main/avto_market/auction/forms.py
from django import forms
from .models import Auction, Buyer, Comment

class AuctionForm(forms.ModelForm):
    class Meta:
        model = Auction
        fields = ['start_price','active', 'end_time', ]
        

class BuyerForm(forms.ModelForm):
    class Meta:
        model = Buyer
        fields = ['last_bid_price']

        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

avto1701-main/avto_market/auction/views.py
from django.shortcuts import render, redirect , get_object_or_404
from django.http import Http404, HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from .forms import AuctionForm , BuyerForm, CommentForm
from .models import Auction, Buyer, Comment
from avto.models import Avto 
from django.contrib.auth.models import User
from account.models import Message, Profile
from django.urls import reverse
from django.core.mail import send_mail

@login_required
def auction_create(request, avto_id):
    avto = get_object_or_404(Avto, id=avto_id)
    if avto.author != request.user:
        return HttpResponseForbidden("У вас нет прав для удаления этого объявления.")
    if request.method == 'POST':
        form = AuctionForm(request.POST)
        if form.is_valid():
            auction = form.save(commit=False)
            auction.avto = avto
            auction.save()
            return redirect('avto:user_avto')
    else:
        form = AuctionForm()
    
    return render(request, 'auction/auction_create.html', {'form': form})

def view_all_auctions(request):
    auctions = Auction.objects.filter(active=True) 
    buyers = Buyer.objects.all()
    return render(request, 'auction/view_all_auctions.html', {'auctions': auctions, 'buyers': buyers})


@login_required
def view_user_auctions(request):
    user = request.user
    auctions = Auction.objects.filter(avto__author=user)  
    context = {
        'auctions': auctions
    }   
    return render(request, 'auction/view_user_auctions.html', context)


@login_required
def edit_auction(request, auction_id):
    auction = get_object_or_404(Auction, id=auction_id)

    if auction.avto.author != request.user and not request.user.is_superuser:
        raise Http404

    if request.method == 'POST':
        form = AuctionForm(request.POST, instance=auction)

        if form.is_valid():
            form.save()
            return redirect('auction:view_user_auctions',)
    else:
        form = AuctionForm(instance=auction)

    context = {
        'form': form,
        'auction': auction
    }

    return render(request, 'auction/edit_auction.html', context)


@login_required
def create_buyer(request, auction_id, user_id):
    auction = get_object_or_404(Auction, id=auction_id)
    user = get_object_or_404(User, id=user_id)

    if request.method == 'POST':
        form = BuyerForm(request.POST)
        if form.is_valid():
            buyer = form.save(commit=False)
            buyer.auction = auction
            buyer.user = user
            if buyer.last_bid_price < auction.start_price:
                form.add_error('last_bid_price', 'Стартовая цена не может быть меньше цены предложения.')
            else:
                buyer.save()
                return redirect('auction:view_all_auctions')
    else:
        form = BuyerForm()

    return render(request, 'auction/create_buyer.html', {'form': form, 'auction': auction, 'user': user})


@login_required
def comment_create(request, auction_id, user_id):
    auction = get_object_or_404(Auction, id=auction_id)
    user = get_object_or_404(User, id=user_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.auction = auction
            comment.author = user
            comment.save()
            return redirect('auction:auction_detail', auction_id=auction_id)
    else:
        form = CommentForm()

    return render(request, 'auction/comment_create.html', {'form': form, 'auction': auction, 'user': user})

@login_required
def auction_detail(request, auction_id):
    auction = Auction.objects.get(id=auction_id)
    avto = auction.avto
    buyers = Buyer.objects.filter(auction=auction)
    comments = Comment.objects.filter(auction=auction)

    return render(request, 'auction/auction_detail.html', {'avto': avto, 'auction': auction, 'buyers': buyers, 'comments': comments,})


def winner(request, auction_id):
    auction = Auction.objects.get(id=auction_id)
    bidders = Buyer.objects.filter(auction=auction).order_by('-last_bid_price')

    if bidders:
        winner = bidders[0].user
    else:
        return render(request, 'auction/no_bidders.html')
        
    auction.active = False
    auction.save()
    admin = User.objects.get(username='admin')
    auction_detail_url = reverse('auction:auction_detail', args=[auction.id])
    absolute_url = request.build_absolute_uri(auction_detail_url)    
    message = Message(sender=admin , recipient= winner, text=f"Вы победили в аукционе - {auction.avto} -{auction.avto.model}, ниже ссылка на выйгранный аукцион", link=absolute_url)
    message.save()

    subject = 'Поздравляем с победой на аукционе'
    message_text = f"Вы победили в аукционе {auction.avto} - {auction.avto.model}. Ниже ссылка на выигранный аукцион:\n{absolute_url}"
    email_from = 'seva2411@yandex.ru'
    recipient_list = [winner.email]
    send_mail(subject, message_text, email_from, recipient_list)



    context = {
        'auction': auction,
        'bidders': bidders,
        'winner': winner
    }

    return render(request, 'auction/winner.html', context)



def profile_win(request, username):
    user = get_object_or_404(User, username=username)
    profile = Profile.objects.get(user=user)
    context = {
        'profile': profile
    }
    return render(request, 'account/profile.html', context)

avto1701-main/avto_market/auction/templates/auction/auction_create.html
{% extends "avto/base.html" %}


{% block content1 %}
<style>
  .form-container {
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    background-color: #f2f2f2;
    border-radius: 5px;
    box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.1);
  }

  .form-container form {
    display: flex;
    flex-direction: column;
    border: 2px solid #333;
    padding: 20px;
  }

  .form-container label,
  .form-container input,
  .form-container button {
    margin-bottom: 10px;
  }

  .form-container label {
    font-weight: bold;
  }

  .form-container input {
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    background-color: white;
  }

  .form-container button {
    padding: 10px 20px;
    background-color: #333;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .form-container button:hover {
    background-color: #555;
  }

  .form-container input[type="text"],
  .form-container input[type="email"] {
    border: 1px solid #777;
    background-color: white;
    color: black;
  }

  .container {
    min-height: 42vh;
  }
  
</style>

<div class="form-container">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Сохранить</button>
  </form>
</div>
{% endblock %}  

avto1701-main/avto_market/auction/templates/auction/auction_detail.html
{% extends 'avto/base.html' %}
{% load static %}

{% block content1 %}

<head>
    <title>{{ avto.brand }} {{ avto.model }}</title>
    <style>


        .title {
            color: #bdc55f;
            font-size: 24px;
            font-weight: bold;
            box-shadow: 0 0 15px white;
            padding: 0.5%;
            background: rgba(0, 0, 0, 0.8);
        }

        .info {
            color: #bdc55f;
            font-size: 16px;
            margin-bottom: 10px;
            font-weight: bold;
            box-shadow: 0 0 15px white;
            padding: 0.5%;
            background: rgba(0, 0, 0, 0.8);
        }

        .image {
            max-width: 70%;
            height: auto;
            margin-top: 10px;
            border-radius: 8px;
            box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
            border: 5px solid black;
            box-shadow: 0 0 15px white;
        }

        .auction-link {
            display: inline-block;
            background-color: #4d1911;;
            color: yellow;
            padding: 10px 20px;
            text-decoration: none;
            font-weight: bold;
            border-radius: 4px;
            margin-top: 10px;
            float: left;
            border: 2px solid black;
            font-size: 17px;
        }

        .auction-link:hover {
            background-color: white;
            color: black !important;
            border: 3px solid black;
            font-size: 18.5px;
        }


        .bid-info {
            background-color: rgba(71, 10, 12, 0.9);
            padding: 10px;
            border: 2px solid black;
            font-size: 16px;
            font-weight: bold;
            box-shadow: 0 0 15px white;
            
        }
        
        .comment-info {
            padding: 10px;
            border: 2px solid black;
            background-color: rgba(14, 1, 40, 0.9);
            font-size: 16px;
            font-weight: bold;
            box-shadow: 0 0 15px white;
        }
        
        .auction-details {
            background-color: rgba(0, 128, 0, 0.4);
            color: yellow;
            border: 2px solid black;
            padding: 10px;
            font-weight: bold;
            font-size: 18px;
            box-shadow: 0 0 15px white;
        }


        .bid-price, .bid-date, .comment-date, .comment-text {
            color: yellow;
            font-size: 16px;
            font-weight: bold;
            
  
        }

        .highlight {
            background-color: #3E0F24;
        }

    </style>
</head>
<body>
    <div>
    <h1 class="title">{{ avto.brand }} {{ avto.model }}</h1>
    <p class="info"><strong>Год выпуска:</strong> <span style="color:white">{{ avto.year }}</style></p>
    <p class="info"><strong>Цена:</strong> <span style="color:white">{{ avto.price }}</style></p>
    <p class="info"><strong>Руль:</strong><span style="color:white"> {{ avto.get_steering_display }}</style></p>
    <p class="info"><strong>Пробег:</strong> <span style="color:white">{{ avto.mileage }}</style></p>
    <p class="info"><strong>Трансмиссия:</strong><span style="color:white"> {{ avto.get_transmission_display }}</style></p>
    <p class="info"><strong>Привод:</strong> <span style="color:white">{{ avto.get_drive_display }}</style></p>
    <p class="info"><strong>Топливо:</strong><span style="color:white"> {{ avto.get_fuel_display }}</style></p>
    <p class="info"><strong>Дата размещения: </strong><span style="color:white">{{ avto.created|date:"Y-m-d" }}</style></p>
    {% if avto.description %}
        <p class="info">Описание: <span style="color:white">{{ avto.description }}</style></p>
    {% endif %}
    {% if avto.image %}
        <img class="image" src="{{ avto.image.url }}" alt="Car Image">
    {% endif %}
    

    <p class="auction-details">
       Стартовая цена: <span style="color:white">{{ auction.start_price }}</style>
    </p>
    
    <p class="auction-details">
        Окончание аукциона: <span style="color:white"> {{ auction.end_time|date:"Y-m-d, H:i" }}</style>
    </p>

    
    {% for buyer in buyers %}
    {% if buyer.auction == auction %}
        <div class="bid-info">
            <p class="bid-price">Последнее предложение: <span style="color:white"> {{ buyer.last_bid_price }}</style></p>
            <p class="bid-date">Дата ставки: <span style="color:white"> {{ buyer.updated_at|date:"Y-m-d, H:i"}} </style></p>
        </div>
    {% endif %}
    {% empty %}
        <p>Нет ставок для этого аукциона</p>
{% endfor %}


{% for comment in comments %}
    {% if comment.auction == auction %}
        <div class="comment-info {% if comment.author == auction.avto.author %}highlight{% endif %}">
            <p class="comment-date">Дата комментария: {{ comment.created_at|date:"Y-m-d, H:i" }}</p>
            <p class="comment-text">{% if comment.author == auction.avto.author %}(От автора) {% endif %}Комментарий: {{ comment.text }}</p>
        </div>
    {% endif %}
    {% empty %}
        <p>Нет комментариев для этого аукциона</p>
{% endfor %}
 
    {% if auction.avto.author != user %}
      <p><a class="auction-link" style="margin: 10px" href="{% url 'auction:create_buyer' auction.id user.id %}" class="edit-button">Сделать ставку</a></p>
    {% endif %}
    <a class="auction-link" style="margin: 10px" href="{% url 'auction:comment_create' auction.id user.id %}">Добавить комментарий</a>
    
    {% if user.is_superuser %}
      <a class="auction-link" href="{% url 'auction:winner' auction.id %}">Найти победителя</a>
    {% endif %}

</body>
</html>

{% endblock %}

avto1701-main/avto_market/auction/templates/auction/comment_create.html
{% extends "avto/base.html" %}


{% block content1 %}
<style>
  .form-container {
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    background-color: #f2f2f2;
    border-radius: 5px;
    box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.1);
  }

  .form-container form {
    display: flex;
    flex-direction: column;
    border: 2px solid #333;
    padding: 20px;
  }

  .form-container label,
  .form-container input,
  .form-container button {
    margin-bottom: 10px;
  }

  .form-container label {
    font-weight: bold;
  }

  .form-container input {
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    background-color: white;
  }

  .form-container button {
    padding: 10px 20px;
    background-color: #333;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .form-container button:hover {
    background-color: #555;
  }

  .form-container input[type="text"],
  .form-container input[type="email"] {
    border: 1px solid #777;
    background-color: white;
    color: black;
  }
  .container {
    min-height: 42vh;
  }
  
</style>

<div class="form-container">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Оставить комментарий</button>
  </form>
</div>
{% endblock %}  

avto1701-main/avto_market/auction/templates/auction/create_buyer.html
{% extends "avto/base.html" %}


{% block content1 %}
<style>
  .form-container {
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    background-color: #f2f2f2;
    border-radius: 5px;
    box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.1);
  }

  .form-container form {
    display: flex;
    flex-direction: column;
    border: 2px solid #333;
    padding: 20px;
  }

  .form-container label,
  .form-container input,
  .form-container button {
    margin-bottom: 10px;
  }

  .form-container label {
    font-weight: bold;
  }

  .form-container input {
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    background-color: white;
  }

  .form-container button {
    padding: 10px 20px;
    background-color: #333;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .form-container button:hover {
    background-color: #555;
  }

  .form-container input[type="text"],
  .form-container input[type="email"] {
    border: 1px solid #777;
    background-color: white;
    color: black;
  }

  .container {
    min-height: 42vh;
  }
  
</style>

<div class="form-container">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Сохранить</button>
  </form>
</div>
{% endblock %}  

avto1701-main/avto_market/auction/templates/auction/edit_auction.html
{% extends "avto/base.html" %}


{% block content1 %}
<style>
  .form-container {
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    background-color: #f2f2f2;
    border-radius: 5px;
    box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.1);
  }

  .form-container form {
    display: flex;
    flex-direction: column;
    border: 2px solid #333;
    padding: 20px;
  }

  .form-container label,
  .form-container input,
  .form-container button {
    margin-bottom: 10px;
  }

  .form-container label {
    font-weight: bold;
  }

  .form-container input {
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    background-color: white;
  }

  .form-container button {
    padding: 10px 20px;
    background-color: #333;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .form-container button:hover {
    background-color: #555;
  }

  .form-container input[type="text"],
  .form-container input[type="email"] {
    border: 1px solid #777;
    background-color: white;
    color: black;
  }

  .container {
    min-height: 42vh;
  }
  
</style>

<div class="form-container">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Сохранить</button>
  </form>
</div>
{% endblock %}  

avto1701-main/avto_market/auction/templates/auction/no_bidders.html
{% extends 'avto/base.html' %}
{% load static %}

{% block content1 %}

<style>
    .no-bidders {
        text-align: center;
        margin-top: 50px;
    }

    .no-bidders h2 {
        font-size: 30px;
        color: #ff0000;
        }
</style>

<div class="no-bidders">
    <h2>Покупателей нет :-(</h2>
</div>

{% endblock %}

avto1701-main/avto_market/auction/templates/auction/view_all_auctions.html
{% extends 'avto/base.html' %}
{% load static %}


{% block content1 %} 

<style>
    .card{
      background-color: #4d1911;
    }
    .edit-button {
      background-color: #000000;
      color: white;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      text-decoration: none;
      font-size: 16px;
      font-weight: bold;
      cursor: pointer;
      margin-bottom: 30px;
    }

    .edit-button:hover {
      background-color: white;
      color: black;
      border: 3px solid black;
      font-size: 17px;
    }

    @media (max-width: 767px) {
      .card-container {
        display: flex;
        justify-content: center;
        flex-wrap: wrap;
      }
      
      .card {
        width: 100%;
        margin: 10px;
      }
    }

  </style>

  <div class="card-container">
    {% for auction in auctions %}
      <div class="card">
       <a href="{% url 'auction:auction_detail' auction.id %}">
          <div class="card-image">
            <img src="{% if auction.avto.image %}{{ auction.avto.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="{{ auction.avto.brand }} {{ auction.avto.model }}">
          </div>
          <div class="card-details">
            <h3>{{ auction.avto.brand }}</h3>
            <p>{{ auction.avto.model }}</p>
            <p>Год выпуска: {{ auction.avto.year }}</p>
            <p>Цена: {{ auction.avto.price }}</p>
            <p>Дата создания: {{ auction.avto.created|date:"F j, Y" }}</p>
            
            <p style="color:yellow;font-size: 16px;font-weight: bold;">Стартовая цена: {{ auction.start_price}}</p>
            <p style="color:yellow;font-size: 16px;font-weight: bold;">Торги заканчиваются: {{ auction.end_time|date:"Y-m-d, H:i"}}</p>


        {% if auction.avto.author != user %}
            <p style="margin-top: 25px ; color: white;"><a  href="{% url 'auction:create_buyer' auction.id user.id %}"class="edit-button">Сделать ставку</a></p>
        {% endif %}
        
        <p style="margin-top: 25px ; color: white;"><a href="{% url 'auction:comment_create' auction.id user.id %}" class="edit-button">Добавить комментарий</a></p>

        {% if user.is_superuser %}
          <p style="margin-top: 25px ; color: white;"><a class="edit-button" href="{% url 'auction:winner' auction.id %}">Найти победителя</a></p>
        {% endif %}
        {% if user.is_superuser %}
          <p style="margin-top: 25px ; color: white;"><a class="edit-button" href="{% url 'auction:edit_auction' auction.id %}">Изменить аукцион на правах админа</a></p>
        {% endif %}
            
          </div>
        </a>
      </div>
    {% empty %}
      <p>Лоты отсутствуют</p>
    {% endfor %}
  </div>

{% endblock %}

avto1701-main/avto_market/auction/templates/auction/view_user_auctions.html
{% extends 'avto/base.html' %}
{% load static %}


{% block content1 %} 

<style>
    .card{
      background-color: #4d1911;
    }

    .auction-link {
      display: inline-block;
      background-color: black;
      color: white !important;
      padding: 10px 20px;
      text-decoration: none;
      font-weight: bold;
      border-radius: 4px;
      margin-top: 10px;
      float: left;
  }

  .auction-link:hover {
    background-color: white;
    color: black !important;
    border: 3px solid black;
    font-size: 17px;
    }

    .container {
      min-height: 42vh;
    }

    @media (max-width: 767px) {
      .card-container {
        display: flex;
        justify-content: center;
        flex-wrap: wrap;
      }
      
      .card {
        width: 100%;
        margin: 10px;
      }
    }
  
  </style>

  <div class="card-container">
    {% for auction in auctions %}
      <div class="card">
        <a href="{% url 'auction:auction_detail' auction.id %}">
          <div class="card-image">
            <img src="{% if auction.avto.image %}{{ auction.avto.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="{{ auction.avto.brand }} {{ auction.avto.model }}">
          </div>
          <div class="card-details">
            <h3>{{ auction.avto.brand }}</h3>
            <p>{{ auction.avto.model }}</p>
            <p>Год выпуска: {{ auction.avto.year }}</p>
            <p>Цена: {{ auction.avto.price }}</p>
            <p>Дата создания: {{ auction.avto.created|date:"F j, Y" }}</p>
            
            <p style="color:yellow;font-size: 16px;font-weight: bold;">Стартовая цена: {{ auction.start_price}}</p>
            
            <p style="color:yellow;font-size: 16px;font-weight: bold;">Торги заканчиваются: {{ auction.end_time}}</p>
            
            

            <a class="auction-link"   href="{% url 'auction:edit_auction' auction.id %}">Изменить аукцион</a>

          </div>
        </a>
      </div>
    {% empty %}
      <p>Лоты отсутствуют</p>
    {% endfor %}
  </div>

{% endblock %}

avto1701-main/avto_market/auction/templates/auction/winner.html
{% extends 'avto/base.html' %}
{% load static %}

{% block content1 %}

<style>
    /* CSS стили здесь */
    .wrapper {
        text-align: center;
        border: 2px solid yellow;
        background-color: #1c1b14;
        padding: 20px;
        margin: 20px auto;
        width: 500px;
    }

    h3 {
        color: yellow;
        margin: 10px
    }

    ul {
        list-style-type: none;
        padding: 0;
    }

    li {
        margin-bottom: 10px;
        font-weight: 700;
        color: yellow;
    }

    .winner-button {
        display: inline-block;
        background-color: #F01C14;
        color: white;
        padding: 10px;
        text-decoration: none;
        border-radius: 5px;
    }

    .winner-button:hover {
        background-color: green;
    }

</style>

<div class="wrapper">
    <h3>Участники: </h3>
    <ul>
        {% for bidder in bidders %}
            <li> Предложение: {{ bidder.last_bid_price }} Покупатель:  {{ bidder.user }}</li>
        {% empty %}
            <li>No bidders found.</li>
        {% endfor %}

        <li><a href="{% url 'auction:profile_win' winner %}" class="winner-button">победитель:  {{ winner }}</a></li>
    </ul>
</div>

{% endblock %}